language: node_js
node_js:
  - '9'
install: npm install
script:
  - npm run tsc
  - npm run test
deploy:
  provider: npm
  email: l.gholoi@outlook.com
  api_key:
    secure: gFX8QQNi8kGQE8fWaKTaWqThXqG7Ua/iDiliTHpfZBuiuKcLUP7nULTCeYGLnVZTb9bxKHeJbjQzWX3yrEdexT7RLYIoci0yGjGBD7hqeaI5upYdQDchUlNj2ZoTT3yUPylYW7qzcmRvgfuIuXKsBqUQgeg8Kda6sIbkZK1r/UG75rEMODD/lAaTpEcHoXSlmUW08eoC6hdMoaQQwQj4E1hKbn37z1Zjbf3RLkuJu/BwO/Gg3HNaFCIMMeMYzfwjBX7smMjWcUwj1uSKIP1n1pO9zORPXMWmc9Qeev1StLTm7UrYc1oCuaieKGhMVV9eI7jNH7tRRxndesYBom79yC8OQoSOAB+kAJqyPhT/RmYUOVLEZI+zxu2hAAEemy7WnDC4QQbyg+srCPl1lNTXDKGS81gKWvn9jYFp7oQoLHR2s6soE7ng9F2I+4bW6e6Y9j/dG8/9oq9ydjjoKsrtzjUgEhcrmYw9ELQWVIRzn2pGYuACRm045TO6tiemUVXYwGwEovci5O0uXPNbfmEemVnEeGIj0cyGFZyaG432T6KZC6b8X+A5y3Rvj86+wvBGV/f9H/qDaskJ31JYct9z0HyLQNOxrj28H8hT6wI+ZbNyryxtE2oubXB0sHlDB39PQdcHImLwfOmg0aP/JJ4dTuT6ourYaV3GhtFvmZF9rjE=
  on:
    tags: true
    branch: master
  skip_cleanup: true
